import Head from 'next/head'
import NewMusics from '@components/NewMusic'
import Layout from '@layout/Layout'
import TopChart_and_promoteArtist from '@components/TopChart_and_promoteArtist'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <TopChart_and_promoteArtist/>
        <NewMusics/>
      </Layout>      
    </>
  )
}
