import Head from 'next/head'
import NewMusics from '@components/NewMusic'
import Layout from '@layout/Layout'
import MainSlider from '@components/MainSlider'
import PopularPodcasts from '@components/PopularPodcasts'
import TopWeekMusics from '@components/TopWeekMusics'
import Top3 from '@components/Top3'
import FreeSlider from '@common/FreeSlider'
import { TSlider } from '@type/public.types'

export default function Home() {

  const data : TSlider[]= [
    {title : "Aleki" , img : "https://cdnmrtehran.ir/media/imgtmp/640f2b0486667.jpg"},
    {title : "Z3ta" , img : "https://cdnmrtehran.ir/media/imgtmp/6416fdfb59d02.jpg"},
    {title : "oone mesle Dadasham bood" , img : "https://cdnmrtehran.ir/media/imgtmp/641db0fadd11c.jpg"},
    {title : "Aleki" , img : "https://cdnmrtehran.ir/media/imgtmp/6415f59163d4d.jpg"},
    {title : "Aleki" , img : "https://cdnmrtehran.ir/media/imgtmp/640f2b0486667.jpg"},
    {title : "Aleki" , img : "https://cdnmrtehran.ir/media/imgtmp/6416fdfb59d02.jpg"},
    {title : "Aleki" , img : "https://cdnmrtehran.ir/media/imgtmp/641db0fadd11c.jpg"},
    {title : "Aleki" , img : "https://cdnmrtehran.ir/media/imgtmp/6415f59163d4d.jpg"},
  ]
  return (
    <>
      <Head>
        <title>Musica</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <MainSlider/>
        <FreeSlider sliders={data} title={"New Musics"}/>
        {/* <Top3/> */}
        <TopWeekMusics/>
        <NewMusics/>
        <PopularPodcasts/>
      </Layout>      
    </>
  )
}
