import Head from 'next/head'
import Layout from '@layout/Layout'
import MainSlider from '@components/MainSlider'
import TopTracksInWeek from '@components/TopTracksInWeek'
import FreeSlider from '@common/FreeSlider'
import { ETypes, TSlider } from '@type/public.types'
import TopTracksInMonth from '@components/TopTracksInMonth'

export default function Home() {

  const data : TSlider[]= [
    {title : "Aleki" , img : "https://cdnmrtehran.ir/media/imgtmp/640f2b0486667.jpg"},
    {title : "Aleki" , img : "https://cdnmrtehran.ir/media/imgtmp/6416fdfb59d02.jpg"},
    {title : "Aleki" , img : "https://cdnmrtehran.ir/media/imgtmp/641db0fadd11c.jpg"},
    {title : "Aleki" , img : "https://cdnmrtehran.ir/media/imgtmp/6415f59163d4d.jpg"},
    {title : "Aleki" , img : "https://cdnmrtehran.ir/media/imgtmp/640f2b0486667.jpg"},
    {title : "Aleki" , img : "https://cdnmrtehran.ir/media/imgtmp/6416fdfb59d02.jpg"},
    {title : "Aleki" , img : "https://cdnmrtehran.ir/media/imgtmp/641db0fadd11c.jpg"},
    {title : "Aleki" , img : "https://cdnmrtehran.ir/media/imgtmp/6415f59163d4d.jpg"},
  ]
  return (
    <>
      <Head>
        <title>Musica</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <MainSlider/>
        <TopTracksInWeek/>
        {/* New Release */}
        <FreeSlider type={ETypes.SONG} sliders={data} title={"New Release."}/>
        {/* New Album */}
        <FreeSlider type={ETypes.PLAYLIST} sliders={data} title={"New Albums."}/>
        {/* popular Padcasts */}
        <FreeSlider type={ETypes.PLAYLIST} sliders={data} title={"popular Padcats."}/>
        {/* Top Tracks In Month */}
        <TopTracksInMonth/>
        {/* Recently Added */}
        <FreeSlider type={ETypes.POTCAST} sliders={data} title={"Recently Added."}/>
        {/* New Podcasts */}
        <FreeSlider type={ETypes.POTCAST} sliders={data} title={"New Podcasts."}/>
        {/* Top Podcasts */}
        <FreeSlider type={ETypes.POTCAST} sliders={data} title={"Top Podcasts."}/>
        {/* Popular Playlist */}
        <FreeSlider type={ETypes.PLAYLIST} sliders={data} title={"Popular Playlists."}/>
        {/* Top Artists */}
        <FreeSlider type={ETypes.SINGER} sliders={data} title={"Top Artists."}/>
      </Layout>      
    </>
  )
}
